import type { Metadata } from "next";
import { Roboto , Inter} from "next/font/google";
import "./globals.css";

//fonts
const inter = Inter({
  subsets:['latin'],
  display:'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en" className={inter.className}>
      <body>{children}</body>
    </html>
  )
}
